"""DEPS-04 / DEPS-05 — AUDIT.md generator.

Reads:
  - pyproject.toml + uv.lock (Python direct deps + transitives + licenses)
  - tauri/src-tauri/Cargo.toml + Cargo.lock (Rust direct deps + licenses)
  - tauri/ui/package.json + package-lock.json (JS direct deps + licenses)
  - scripts/audit/dep_ratings.yaml (hand-authored rating + rationale)

Writes: docs/AUDIT.md — single source of truth for direct-dep
rationale + install-impact rating across all 3 ecosystems.

Invariants:
  - Generator output is byte-stable across runs on an unchanged tree.
  - No Gemini model literals in the output (ModelRouter seam — verified
    by .github/workflows/model-literal-check.yml).
  - No AI-slop tokens in the output (Anti-slop blocklist — verified by
    scripts/launch/check_no_ai_slop.py extended scan target).

Usage:
  uv run python scripts/audit/gen_audit_md.py [--check]

--check mode: regenerates to a tempfile and diffs against the committed
AUDIT.md; exits 1 on drift. The CI freshness gate (Plan 03 Task 4)
invokes this with --check.
"""

from __future__ import annotations

import argparse
import json
import sys
import tomllib
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
PYPROJECT = REPO / "pyproject.toml"
UV_LOCK = REPO / "uv.lock"
CARGO_TOML = REPO / "tauri" / "src-tauri" / "Cargo.toml"
PKG_JSON = REPO / "tauri" / "ui" / "package.json"
DEP_RATINGS = REPO / "scripts" / "audit" / "dep_ratings.yaml"
AUDIT_MD = REPO / "docs" / "AUDIT.md"

RATING_EMOJI = {"green": "🟢", "yellow": "🟡", "red": "🔴"}

PREAMBLE = """# vibemix Dependency Audit

> Single source of truth for direct-dep rationale + license +
> install-impact rating across Python / Rust / JS.
>
> Generated by `scripts/audit/gen_audit_md.py` from `pyproject.toml`,
> `tauri/src-tauri/Cargo.toml`, `tauri/ui/package.json`, and the
> hand-authored `scripts/audit/dep_ratings.yaml` ratings side-file.
>
> **Do not edit by hand.** Edit `scripts/audit/dep_ratings.yaml` and
> rerun the generator.

## Install-Impact rating rubric

| Rating | Definition |
|--------|------------|
| 🟢 Green | Pure-Python wheel or pure-JS/pure-Rust crate. Zero native build, zero OS extension, zero driver, zero user prompt during the installer happy path. |
| 🟡 Yellow | Native wheel or Rust crate with `cc` / system-lib dep, prebuilt for Mac arm64+x86_64 AND Win64. Installer-invisible. |
| 🔴 Red | Requires system extension, kernel driver, OS-Settings approval, manual brew/winget install, or any user-consent prompt. Driver-level deps (BlackHole / VB-CABLE / system MIDI) live in Phase 49's installer-companion table — NOT this file. |
"""


def section(label: str, rows: list[str]) -> str:
    lines = [
        "",
        f"## {label}",
        "",
        "| Package | Version | License | Rationale | Install-Impact | Notes |",
        "|---------|---------|---------|-----------|----------------|-------|",
    ]
    lines.extend(rows)
    lines.append("")
    return "\n".join(lines)


DECISIONS_HEADER = """
## Decisions

Per-dep deferral / cull decisions land here. Plan 04 of Phase 46
populates the dep-cull entries; future re-justifications append.
"""

GH_ACTIONS_HEADER = """
## GitHub Actions

Workflow `uses:` lines are SHA-pinned via `pinact` v3.x (Plan 05).
The audit at `scripts/audit/run_pinact.sh --check` fails any PR
that re-introduces a floating `@vX` tag reference.
"""


def load_ratings() -> dict:
    with DEP_RATINGS.open() as f:
        return yaml.safe_load(f)


def load_pyproject_deps() -> list[str]:
    """Direct deps from pyproject.toml [project.dependencies]."""
    with PYPROJECT.open("rb") as f:
        data = tomllib.load(f)
    deps = data["project"]["dependencies"]
    names = []
    for d in deps:
        # Strip version specifiers and extras
        name = (
            d.split("[")[0]
            .split(">=")[0]
            .split("==")[0]
            .split("<")[0]
            .split(">")[0]
            .split("~=")[0]
            .split(";")[0]
            .strip()
        )
        names.append(name)
    return names


def load_uv_lock_packages() -> dict[str, dict]:
    """All packages in uv.lock keyed by name (lowercased)."""
    try:
        with UV_LOCK.open("rb") as f:
            data = tomllib.load(f)
    except FileNotFoundError:
        return {}
    packages: dict[str, dict] = {}
    for pkg in data.get("package", []):
        packages[pkg["name"].lower()] = pkg
    return packages


def load_cargo_deps() -> list[str]:
    """Direct deps from tauri/src-tauri/Cargo.toml [dependencies]."""
    with CARGO_TOML.open("rb") as f:
        data = tomllib.load(f)
    deps = list(data.get("dependencies", {}).keys())
    deps += list(data.get("build-dependencies", {}).keys())
    return deps


def load_pkg_deps() -> list[str]:
    """Direct deps from tauri/ui/package.json (runtime + dev)."""
    with PKG_JSON.open() as f:
        data = json.load(f)
    runtime = list(data.get("dependencies", {}).keys())
    dev = list(data.get("devDependencies", {}).keys())
    return runtime + dev


def render_row(
    name: str,
    version: str,
    license_: str,
    rating: str,
    rationale: str,
    notes: str = "",
) -> str:
    emoji = RATING_EMOJI.get(rating, "❓")
    rationale = rationale.replace("|", "\\|")
    notes = notes.replace("|", "\\|")
    return f"| `{name}` | {version} | {license_} | {rationale} | {emoji} {rating.capitalize()} | {notes} |"


def render_python(ratings: dict) -> str:
    deps = load_pyproject_deps()
    lock_pkgs = load_uv_lock_packages()
    rows = []
    for dep in sorted(deps, key=str.lower):
        r = ratings.get(dep, {})
        if not r:
            rows.append(
                render_row(
                    dep, "?", "?", "yellow",
                    "[NO RATING — add to dep_ratings.yaml]", "MISSING",
                )
            )
            continue
        pkg = lock_pkgs.get(dep.lower(), {})
        version = pkg.get("version", "?") if isinstance(pkg, dict) else "?"
        license_raw = pkg.get("license") if isinstance(pkg, dict) else None
        if not license_raw and isinstance(pkg, dict):
            license_raw = pkg.get("metadata", {}).get("license") if isinstance(pkg.get("metadata"), dict) else None
        license_ = license_raw if license_raw else "see uv.lock"
        rows.append(render_row(dep, version, license_, r["rating"], r["rationale"]))
    return section("Python", rows)


def render_rust(ratings: dict) -> str:
    deps = load_cargo_deps()
    rows = []
    for dep in sorted(deps, key=str.lower):
        r = ratings.get(dep, {})
        if not r:
            rows.append(
                render_row(
                    dep, "?", "?", "yellow",
                    "[NO RATING — add to dep_ratings.yaml]", "MISSING",
                )
            )
            continue
        rows.append(
            render_row(
                dep, "see Cargo.lock", "see Cargo.toml",
                r["rating"], r["rationale"],
            )
        )
    return section("Rust", rows)


def render_js(ratings: dict) -> str:
    deps = load_pkg_deps()
    rows = []
    for dep in sorted(deps, key=str.lower):
        r = ratings.get(dep, {})
        if not r:
            rows.append(
                render_row(
                    dep, "?", "?", "yellow",
                    "[NO RATING — add to dep_ratings.yaml]", "MISSING",
                )
            )
            continue
        rows.append(
            render_row(
                dep, "see package-lock.json", "see package-lock.json",
                r["rating"], r["rationale"],
            )
        )
    return section("JavaScript", rows)


def render_decisions(decisions: list[dict]) -> str:
    out = [DECISIONS_HEADER]
    for d in decisions:
        out.append(f"\n### {d['id']}\n")
        out.append(f"**Date:** {d['date']}  ")
        out.append(f"**Target:** `{d['target']}`  ")
        out.append(f"**Action:** {d['action']}\n")
        out.append(d["rationale"].rstrip() + "\n")
    return "\n".join(out)


def generate() -> str:
    ratings = load_ratings()
    decisions = ratings.get("decisions", []) if isinstance(ratings, dict) else []
    parts = [
        PREAMBLE,
        render_python(ratings.get("python", {})),
        render_rust(ratings.get("rust", {})),
        render_js(ratings.get("js", {})),
        render_decisions(decisions),
        GH_ACTIONS_HEADER,
        "\n---\n\n*Last generated by `scripts/audit/gen_audit_md.py`.*\n",
    ]
    return "\n".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail on drift between generated output and committed AUDIT.md",
    )
    args = parser.parse_args()
    new = generate()
    if args.check:
        if not AUDIT_MD.exists():
            print(
                f"::error::{AUDIT_MD} missing — run `python scripts/audit/gen_audit_md.py` and commit",
                file=sys.stderr,
            )
            return 1
        if new != AUDIT_MD.read_text():
            print(
                f"::error::{AUDIT_MD} drifted from generator output — re-run `python scripts/audit/gen_audit_md.py` and commit",
                file=sys.stderr,
            )
            return 1
        print(f"{AUDIT_MD} is in sync with generator + dep_ratings.yaml")
        return 0
    AUDIT_MD.parent.mkdir(parents=True, exist_ok=True)
    AUDIT_MD.write_text(new)
    print(f"wrote {AUDIT_MD} ({len(new)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
