/**
 * VIS-02 (Phase 43, Plan 43-02): hover-glow coverage spec.
 *
 * Scaffolded; runs in CI, not at execute time per CONTEXT note (Tauri
 * UI Playwright infra lives downstream of this commit — see Phase 43
 * §VIS-01 audit driver). This spec pins that every interactive element
 * in the session + overlay surfaces carries `--glow-faint` on :hover
 * AND :focus-visible.
 *
 * Element categories covered:
 *   1. <button> not disabled
 *   2. <a>          (anchor — currently the session window carries
 *                    no <a> elements; the test stays in the suite as a
 *                    forward-compat assertion that ANY future anchor
 *                    obeys the hover-glow contract.)
 *   3. [role="button"] not aria-disabled
 *   4. [data-interactive]
 *
 * Token reference: `--glow-faint: 0 0 5px var(--amber-22);` (tokens.css).
 * `--amber-22` resolves to `rgba(255, 138, 61, 0.22)` per the v5 CDJ
 * Whisper palette. The computed `box-shadow` of a hovered element therefore
 * includes the substring `rgba(255, 138, 61` somewhere in its value (the
 * exact alpha may render as `0.22` or computed `0.219999...` depending on
 * the engine's float→string serialiser; the substring check skips the
 * alpha to stay engine-agnostic).
 *
 * The assertion strategy is computed-style probe at :hover state:
 *   - Locate the element
 *   - Hover it
 *   - Read `getComputedStyle(el).boxShadow`
 *   - Assert it contains the resolved amber-22 RGB triple
 * Snapshot baseline lives in `__snapshots__/` and is generated by CI
 * on first green run.
 *
 * Wiring strategy: this spec assumes the Playwright config points
 * `baseURL` at the Tauri dev server (vite-dev default `/`) where the
 * session window is the index entry. Same convention as
 * meter-spectrum.spec.ts (VIS-03).
 */
import { test, expect } from "@playwright/test";

const AMBER_22_RGB_SUBSTRING = "rgba(255, 138, 61"; // alpha-agnostic

test.describe("hover-glow coverage", () => {
  test.beforeEach(async ({ page }) => {
    // Session window root — Tauri dev server serves index.html at /.
    await page.goto("/");
    // Wait for the session surface to mount before probing hover states.
    await page.locator(".vmx-session").waitFor();
  });

  test("button: --glow-faint on :hover", async ({ page }) => {
    const btn = page.locator("button:not([disabled])").first();
    await btn.hover();
    const shadow = await btn.evaluate(
      (el) => getComputedStyle(el).boxShadow,
    );
    expect(shadow).toContain(AMBER_22_RGB_SUBSTRING);
    await expect(btn).toHaveScreenshot("button-hover.png");
  });

  test("anchor: --glow-faint on :hover", async ({ page }) => {
    // The session window currently carries no <a> elements (titlebar,
    // pickers, rockers, status-bar use <button>). When a future surface
    // (settings drawer link-out, wizard "learn more" links) adds an
    // anchor, this test asserts it inherits the same hover-glow contract.
    // Until then the test guards against regression — `count === 0`
    // passes as a no-op rather than failing.
    const count = await page.locator("a").count();
    test.skip(count === 0, "no <a> elements on the session surface yet");
    const a = page.locator("a").first();
    await a.hover();
    const shadow = await a.evaluate(
      (el) => getComputedStyle(el).boxShadow,
    );
    expect(shadow).toContain(AMBER_22_RGB_SUBSTRING);
    await expect(a).toHaveScreenshot("anchor-hover.png");
  });

  test("role=button: --glow-faint on :hover", async ({ page }) => {
    // Rocker segments are `<button role="radio">`, NOT role=button. The
    // role=button selector targets any future synthetic interactive
    // element that opts into ARIA without using a real <button> — same
    // forward-compat shape as the anchor test above.
    const count = await page
      .locator('[role="button"]:not([aria-disabled="true"])')
      .count();
    test.skip(count === 0, "no [role=button] elements on the session surface yet");
    const rb = page
      .locator('[role="button"]:not([aria-disabled="true"])')
      .first();
    await rb.hover();
    const shadow = await rb.evaluate(
      (el) => getComputedStyle(el).boxShadow,
    );
    expect(shadow).toContain(AMBER_22_RGB_SUBSTRING);
    await expect(rb).toHaveScreenshot("role-button-hover.png");
  });

  test("data-interactive: --glow-faint on :hover", async ({ page }) => {
    // `[data-interactive]` is reserved as a session-wide opt-in for
    // anything that needs the hover-glow but isn't a <button> / <a> /
    // [role="button"] (e.g. a future drag-handle on the cohost
    // transcript). When the first consumer ships, the count flips
    // non-zero and the assertion engages.
    const count = await page.locator("[data-interactive]").count();
    test.skip(count === 0, "no [data-interactive] elements on the session surface yet");
    const di = page.locator("[data-interactive]").first();
    await di.hover();
    const shadow = await di.evaluate(
      (el) => getComputedStyle(el).boxShadow,
    );
    expect(shadow).toContain(AMBER_22_RGB_SUBSTRING);
    await expect(di).toHaveScreenshot("data-interactive-hover.png");
  });
});
