/**
 * VIS-03 (Phase 43, Plan 43-04) — meter spectrum visual regression.
 *
 * Scaffolded; runs in CI, not at execute time — scaffolded; runs in CI
 * is the marker the plan's verify gate greps for. Tauri UI Playwright
 * infra lives downstream of this commit — see Phase 43 §VIS-01 audit
 * driver plans). Pins the hardware-LED-strip render at three RMS
 * samples + peak-hold lozenge state. Snapshot baseline lives in
 * `__snapshots__/` and is generated by CI on first green run.
 *
 * Frame-rate smoke (≥60fps via requestAnimationFrame): the trailing
 * test records 60 rAF callbacks and asserts the elapsed time stays
 * under 1100ms (≥54fps tolerance band — leaves ~10% headroom for CI
 * jitter without weakening the "no AI slop, no jank" gate).
 *
 * Wiring strategy for `__setMeterLevels` (CI maintainer picks one
 * before turning this spec on; default = strategy A):
 *
 *   A. Dev-only window hook in main.ts —
 *      `if (import.meta.env.DEV) (window as any).__setMeterLevels = ...`
 *      Exposes the imported `setMeterLevels` directly. Cleanest, but
 *      only available in dev/test bundles.
 *
 *   B. Synthetic ws-bridge frame — dispatch a fake `{meters: {...}}`
 *      event through the existing session ws-bridge so the meter
 *      updates via the production render path. Closer to integration
 *      reality, but requires a stub bridge in the Playwright config.
 *
 * TODO(VIS-03): pick one before snapshot baseline generation. The
 * `page.evaluate(() => (window as any).__setMeterLevels(...))` calls
 * below assume strategy A.
 */
import { test, expect } from "@playwright/test";

test.describe("meter spectrum — VIS-03", () => {
  test.beforeEach(async ({ page }) => {
    // Session window root — Tauri dev server serves index.html at /.
    await page.goto("/");
    // Wait for the music meter to mount before driving levels.
    await page.locator(".vmx-meter[data-label='music']").waitFor();
  });

  test("safe zone — rms=0.3 lights bottom 5 segments only", async ({
    page,
  }) => {
    await page.evaluate(() => {
      const meter = document.querySelector<HTMLElement>(
        ".vmx-meter[data-label='music']",
      );
      if (!meter) throw new Error("meter not found");
      // strategy A — dev-only hook. See file-header TODO(VIS-03).
      (window as unknown as {
        __setMeterLevels: (
          el: HTMLElement,
          levels: { rms: number; peak?: number | null },
        ) => number;
      }).__setMeterLevels(meter, { rms: 0.3, peak: 0.32 });
    });
    const meter = page.locator(".vmx-meter[data-label='music']");
    await expect(meter).toHaveScreenshot("meter-safe-0.3.png");
  });

  test("warm zone — rms=0.7 lights segments through warm band", async ({
    page,
  }) => {
    await page.evaluate(() => {
      const meter = document.querySelector<HTMLElement>(
        ".vmx-meter[data-label='music']",
      );
      if (!meter) throw new Error("meter not found");
      (window as unknown as {
        __setMeterLevels: (
          el: HTMLElement,
          levels: { rms: number; peak?: number | null },
        ) => number;
      }).__setMeterLevels(meter, { rms: 0.7, peak: 0.74 });
    });
    const meter = page.locator(".vmx-meter[data-label='music']");
    await expect(meter).toHaveScreenshot("meter-warm-0.7.png");
  });

  test("clip zone + peak hold — rms=0.95 with peak=1.0 lights all 16 + lozenge at top", async ({
    page,
  }) => {
    await page.evaluate(() => {
      const meter = document.querySelector<HTMLElement>(
        ".vmx-meter[data-label='music']",
      );
      if (!meter) throw new Error("meter not found");
      (window as unknown as {
        __setMeterLevels: (
          el: HTMLElement,
          levels: { rms: number; peak?: number | null },
        ) => number;
      }).__setMeterLevels(meter, { rms: 0.95, peak: 1.0 });
    });
    const meter = page.locator(".vmx-meter[data-label='music']");
    await expect(meter).toHaveScreenshot("meter-clip-peak-0.95-1.0.png");
  });

  test("frame-rate smoke — 60 rAF ticks stay under 1100ms (≥54fps tolerance)", async ({
    page,
  }) => {
    const elapsedMs = await page.evaluate(
      () =>
        new Promise<number>((resolve) => {
          const start = performance.now();
          let ticks = 0;
          const tick = () => {
            ticks++;
            if (ticks < 60) {
              requestAnimationFrame(tick);
            } else {
              resolve(performance.now() - start);
            }
          };
          requestAnimationFrame(tick);
        }),
    );
    // 60 ticks ÷ 1.1s = 54.5fps; tolerates ~10% CI jitter without
    // letting genuine jank slip past. Tightening to <1000ms = strict
    // 60fps would flake on shared CI runners.
    expect(elapsedMs).toBeLessThan(1100);
  });
});
