// SPDX-License-Identifier: Apache-2.0
//
// Generated by scripts/export_learn_curriculum_meta.py.
// Source of truth: src/vibemix/learn/curriculum.py.

import type { ProgressListEntry, LessonStatus } from "./progress-list.js";

type CourseUnlockGate = "course_2_unlocked" | "course_3_unlocked";
type CourseFrontstageMode = "live_play_mode" | "practice_booth";
type CourseCapability = "controller_state" | "cue_section_lookahead" | "debrief" | "dj_profile" | "evidence_registry" | "library_exemplars" | "library_suggestions" | "live_audio" | "on_screen_deck" | "prepared_pool" | "recital_observer" | "recovery_drill" | "session_recording" | "session_state";

interface CourseRegistryRow {
  label: string;
  hud_label: string;
  unlock_gate: CourseUnlockGate | null;
  lock_reason: string | null;
  frontstage_mode: CourseFrontstageMode;
  capabilities: readonly CourseCapability[];
}

export const COURSE_REGISTRY = {
  "course_1_anatomy": { label: "Course 1 · Anatomy", hud_label: "COURSE 1 · ANATOMY", unlock_gate: null, lock_reason: null, frontstage_mode: "practice_booth", capabilities: ["evidence_registry", "controller_state", "on_screen_deck", "library_exemplars", "recital_observer"] },
  "course_2_transitions": { label: "Course 2 · Transitions", hud_label: "COURSE 2 · TRANSITIONS", unlock_gate: "course_2_unlocked", lock_reason: "finish the course 1 check to unlock transitions", frontstage_mode: "practice_booth", capabilities: ["evidence_registry", "controller_state", "on_screen_deck", "library_suggestions", "recital_observer"] },
  "course_3_play_mode": { label: "Course 3 · Play Mode", hud_label: "COURSE 3 · PLAY-MODE", unlock_gate: "course_3_unlocked", lock_reason: "finish the course 2 check to unlock play mode", frontstage_mode: "live_play_mode", capabilities: ["evidence_registry", "controller_state", "on_screen_deck", "live_audio", "cue_section_lookahead", "prepared_pool", "library_suggestions", "session_state", "session_recording", "debrief", "dj_profile", "recovery_drill"] },
} as const satisfies Readonly<Record<string, CourseRegistryRow>>;

export type CourseId = keyof typeof COURSE_REGISTRY;

export const COURSE_LABELS = Object.freeze(
  Object.fromEntries(
    Object.entries(COURSE_REGISTRY).map(([courseId, row]) => [
      courseId,
      row.label,
    ]),
  ),
) as Readonly<Record<CourseId, string>>;

interface CurriculumMetaRow {
  lesson_id: string; // "L1.01" - what curriculum.py keys CURRICULUM with
  course_id: CourseId;
  title: string;
}

export interface LearnProgressProjection {
  lessons?: Record<
    string,
    {
      completed?: boolean;
      completed_at?: string | null;
      strikes_used?: number;
      practice_sources?: { hardware?: number; screen?: number };
      last_practice_source?: "hardware" | "screen" | null;
    } | undefined
  >;
  course_2_unlocked?: boolean;
  course_3_unlocked?: boolean;
  next_practice_mission?: LearnPracticeMission;
  [key: string]: unknown;
}

export interface LearnPracticeMission {
  lesson_id: string;
  course_id: string;
  course_label: string;
  skill_id: string;
  skill_label: string;
  title: string;
  mode: "start" | "finish" | "replay" | "prove" | "mastered";
  command: string;
  payoff: string;
  proof: string;
  why: string;
  estimated_minutes: number;
  focus: "first_rep" | "retry" | "proof" | "replay" | "hardware" | "lock" | "mastery";
  focus_label: string;
  challenge: string;
  chain?: LearnPracticeChainStep[];
  meter_label: string;
  meter_value: number;
  meter_max: number;
  meter_state: "armed" | "retry" | "proof" | "mastered" | "replay";
  meter_caption: string;
}

export interface LearnPracticeChainStep {
  lesson_id: string;
  course_id: string;
  course_label: string;
  title: string;
  state: "now" | "next" | "locked";
  mode: "start" | "finish" | "replay" | "prove" | "mastered";
  label: string;
}

/** Canonical lesson order generated from Python CURRICULUM. */
export const CURRICULUM_META: ReadonlyArray<CurriculumMetaRow> = [
  { lesson_id: "L1.01", course_id: "course_1_anatomy", title: "opening dialog" },
  { lesson_id: "L1.02", course_id: "course_1_anatomy", title: "meet your controller" },
  { lesson_id: "L1.03", course_id: "course_1_anatomy", title: "channel strip" },
  { lesson_id: "L1.04", course_id: "course_1_anatomy", title: "crossfader" },
  { lesson_id: "L1.05", course_id: "course_1_anatomy", title: "pitch fader" },
  { lesson_id: "L1.06", course_id: "course_1_anatomy", title: "transport buttons" },
  { lesson_id: "L1.07", course_id: "course_1_anatomy", title: "jog wheel" },
  { lesson_id: "L1.08", course_id: "course_1_anatomy", title: "headphone cueing" },
  { lesson_id: "L1.09", course_id: "course_1_anatomy", title: "master · booth · headphones" },
  { lesson_id: "L1.10", course_id: "course_1_anatomy", title: "anatomy of a song" },
  { lesson_id: "L1.11", course_id: "course_1_anatomy", title: "counting bars" },
  { lesson_id: "L1.12", course_id: "course_1_anatomy", title: "spot breakdown by ear" },
  { lesson_id: "L1.13", course_id: "course_1_anatomy", title: "spot breakdown by eye" },
  { lesson_id: "L1.14", course_id: "course_1_anatomy", title: "eq as tutor" },
  { lesson_id: "L1.15", course_id: "course_1_anatomy", title: "load two tracks" },
  { lesson_id: "L1.16", course_id: "course_1_anatomy", title: "course 1 recital" },
  { lesson_id: "L2.01", course_id: "course_2_transitions", title: "beatmatching by ear" },
  { lesson_id: "L2.02", course_id: "course_2_transitions", title: "beatmatching with sync" },
  { lesson_id: "L2.03", course_id: "course_2_transitions", title: "long blend" },
  { lesson_id: "L2.04", course_id: "course_2_transitions", title: "eq swap" },
  { lesson_id: "L2.05", course_id: "course_2_transitions", title: "bassline swap" },
  { lesson_id: "L2.06", course_id: "course_2_transitions", title: "filter fade" },
  { lesson_id: "L2.07", course_id: "course_2_transitions", title: "echo-out" },
  { lesson_id: "L2.08", course_id: "course_2_transitions", title: "drop swap" },
  { lesson_id: "L2.09", course_id: "course_2_transitions", title: "loop transition" },
  { lesson_id: "L2.10", course_id: "course_2_transitions", title: "hot cues and memory cues" },
  { lesson_id: "L2.11", course_id: "course_2_transitions", title: "camelot wheel" },
  { lesson_id: "L2.12", course_id: "course_2_transitions", title: "phrase matching" },
  { lesson_id: "L2.13", course_id: "course_2_transitions", title: "diagnosing a train wreck" },
  { lesson_id: "L2.14", course_id: "course_2_transitions", title: "course 2 recital" },
  { lesson_id: "L3.01", course_id: "course_3_play_mode", title: "first 5-minute mix" },
  { lesson_id: "L3.02", course_id: "course_3_play_mode", title: "first 15-minute set" },
  { lesson_id: "L3.03", course_id: "course_3_play_mode", title: "reading the room" },
  { lesson_id: "L3.04", course_id: "course_3_play_mode", title: "first 30-minute set capstone" },
  { lesson_id: "L3.05", course_id: "course_3_play_mode", title: "recovery drills" },
  { lesson_id: "L3.06", course_id: "course_3_play_mode", title: "dj profile graduation" },
];

export function firstRecommendedLessonId(
  progress: LearnProgressProjection | null = null,
): string {
  const entries = buildProgressEntries(progress);
  return (
    entries.find((entry) => entry.is_recommended)?.lesson_id ??
    entries.find((entry) => !entry.locked)?.lesson_id ??
    CURRICULUM_META[0]?.lesson_id ??
    "L1.01"
  );
}

/** Project the static curriculum mirror onto the progress-list shape. */
export function buildProgressEntries(
  progress: LearnProgressProjection | null,
): ProgressListEntry[] {
  const lessonsMap = progress?.lessons ?? {};
  const projected: ProgressListEntry[] = CURRICULUM_META.map((meta) => {
    const legacyKey = Object.keys(lessonsMap).find((key) =>
      key.startsWith(`${meta.lesson_id}-`),
    );
    const entry = lessonsMap[meta.lesson_id] ?? (
      legacyKey ? lessonsMap[legacyKey] : undefined
    );
    let status: LessonStatus = "empty";
    if (entry?.completed) {
      status = "completed";
    } else if (
      entry?.completed === false ||
      (entry?.strikes_used && entry.strikes_used > 0)
    ) {
      status = "in-progress";
    }
    const courseUnlocked = isCourseUnlocked(meta.course_id, progress);
    const locked = !courseUnlocked && status !== "completed";
    return {
      lesson_id: meta.lesson_id,
      title: meta.title,
      course_id: meta.course_id,
      course_label: COURSE_LABELS[meta.course_id],
      status,
      strikes_used: entry?.strikes_used,
      locked,
      lock_reason: locked ? lockReason(meta.course_id) : undefined,
    };
  });
  const recommended = (
    projected.find(
      (entry) => !entry.locked && entry.status === "in-progress",
    ) ??
    projected.find(
      (entry) => !entry.locked && entry.status !== "completed",
    ) ??
    projected.find((entry) => !entry.locked)
  );
  if (recommended) recommended.is_recommended = true;
  return projected;
}

function isCourseUnlocked(
  course_id: CourseId,
  progress: LearnProgressProjection | null,
): boolean {
  const gate = COURSE_REGISTRY[course_id]?.unlock_gate;
  if (!gate) return true;
  return progress?.[gate] === true;
}

function lockReason(course_id: CourseId): string {
  return COURSE_REGISTRY[course_id]?.lock_reason ?? "locked";
}
