# SPDX-License-Identifier: Apache-2.0
"""Tests for vibemix.audio.lookahead.LookaheadProvider.

Verbatim-behavior port of cohost_v4_tr.py:624-770 — 7 tests cover:
    1. Happy path — file resolves, ffmpeg returns valid 16kHz mono WAV.
    2. No nowplaying — `_poll_raw` returns None → (None, meta).
    3. No mdfind match (streaming track) — `_resolve_file` returns None → (None, meta).
    4. ffmpeg non-zero returncode (e.g. moov-atom-not-found) → (None, meta).
    5. ffmpeg subprocess.TimeoutExpired → (None, meta).
    6. subprocess.run is called with LIST argv (no shell=True) — V10 mitigation.
    7. ffmpeg argv has `-ss` BEFORE `-i` — RESEARCH Pattern 3 invariant.

Plus an extrapolation-guard correctness test (Pitfall 2 defense) for
`_current_position` on title change.

Tests stay HERMETIC: no real nowplaying-cli / mdfind / ffmpeg subprocess
call ever fires from a test body (the optional fixture-generation step
in conftest is the only ffmpeg subprocess we tolerate, and it skips
cleanly on Linux runners that lack ffmpeg).
"""

from __future__ import annotations

import io
import os
import shutil
import subprocess
import time
import wave
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from vibemix.audio import (
    LOOKAHEAD_SAMPLE_RATE,
    LOOKAHEAD_SECONDS,
    LOOKAHEAD_TIMEOUT_S,
    LOOKAHEAD_WINDOW_SECONDS,
    LookaheadProvider,
)


# ---------------------------------------------------------------------------
# Fixture mp3 — generated on-demand via ffmpeg sine. Skips on CI without ffmpeg.
# ---------------------------------------------------------------------------


def _fixture_path() -> Path:
    return Path(__file__).parent / "fixtures" / "test_lookahead_track.mp3"


@pytest.fixture(scope="module")
def lookahead_fixture_mp3() -> Path:
    """A 5s 440Hz sine mp3 generated by ffmpeg; skips if ffmpeg unavailable.

    Module-scoped — generated once per test session for the happy-path test.
    """
    path = _fixture_path()
    if path.exists() and path.stat().st_size > 1024:
        return path
    ffmpeg = shutil.which("ffmpeg")
    if not ffmpeg:
        pytest.skip("ffmpeg not available — happy-path test requires fixture gen")
    path.parent.mkdir(parents=True, exist_ok=True)
    proc = subprocess.run(
        [
            ffmpeg, "-y", "-loglevel", "error",
            "-f", "lavfi", "-i", "sine=frequency=440:duration=5",
            "-c:a", "libmp3lame", "-b:a", "64k", str(path),
        ],
        capture_output=True, timeout=10.0,
    )
    if proc.returncode != 0 or not path.exists():
        pytest.skip(
            f"ffmpeg fixture-gen failed (rc={proc.returncode}): "
            f"{proc.stderr.decode(errors='replace')[:200]}"
        )
    return path


# ---------------------------------------------------------------------------
# Test 1 — happy path
# ---------------------------------------------------------------------------


def test_snapshot_wav_happy_path(
    monkeypatch: pytest.MonkeyPatch, lookahead_fixture_mp3: Path
) -> None:
    """Fixture mp3 + monkeypatched position → valid 16kHz mono WAV bytes."""
    provider = LookaheadProvider()

    monkeypatch.setattr(
        provider, "_current_position", lambda: ("FixtureTrack", 1.0, 1.0)
    )
    monkeypatch.setattr(
        provider, "_resolve_file", lambda title: str(lookahead_fixture_mp3)
    )

    wav, meta = provider.snapshot_wav()
    assert wav is not None, f"happy path returned None; meta={meta}"
    assert wav.startswith(b"RIFF"), "expected WAV RIFF header"
    assert meta["ok"] is True
    assert meta["reason"] == "ok"
    assert meta["title"] == "FixtureTrack"

    with wave.open(io.BytesIO(wav), "rb") as wf:
        assert wf.getframerate() == LOOKAHEAD_SAMPLE_RATE == 16000
        assert wf.getnchannels() == 1
        assert wf.getsampwidth() == 2  # int16
        assert wf.getnframes() > 0


# ---------------------------------------------------------------------------
# Tests 2-5 — graceful-degrade paths
# ---------------------------------------------------------------------------


def test_no_nowplaying_returns_none(monkeypatch: pytest.MonkeyPatch) -> None:
    """`_poll_raw` → None ⇒ snapshot returns (None, meta with no-nowplaying reason)."""
    provider = LookaheadProvider()
    monkeypatch.setattr(provider, "_poll_raw", lambda: None)

    wav, meta = provider.snapshot_wav()
    assert wav is None
    assert meta["ok"] is False
    assert meta["reason"] == "no nowplaying"


def test_no_file_match_returns_none(monkeypatch: pytest.MonkeyPatch) -> None:
    """Streaming-only track (no mdfind hit) ⇒ snapshot returns (None, meta no-file)."""
    provider = LookaheadProvider()
    monkeypatch.setattr(
        provider, "_current_position", lambda: ("UnknownTrack", 5.0, 1.0)
    )
    monkeypatch.setattr(provider, "_resolve_file", lambda title: None)

    wav, meta = provider.snapshot_wav()
    assert wav is None
    assert meta["ok"] is False
    assert "no file" in meta["reason"]


def test_ffmpeg_error_returns_none(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """ffmpeg non-zero returncode (e.g. moov atom not found) ⇒ (None, meta)."""
    provider = LookaheadProvider()
    fake_file = tmp_path / "corrupt.m4a"
    fake_file.write_bytes(b"\x00\x00\x00\x00not actually an mp4")

    monkeypatch.setattr(
        provider, "_current_position", lambda: ("CorruptTrack", 1.0, 1.0)
    )
    monkeypatch.setattr(provider, "_resolve_file", lambda title: str(fake_file))

    fake_proc = MagicMock()
    fake_proc.returncode = 1
    fake_proc.stdout = b""
    fake_proc.stderr = b"moov atom not found"

    with patch(
        "vibemix.audio.lookahead.subprocess.run", return_value=fake_proc
    ) as mock_run:
        wav, meta = provider.snapshot_wav()

    assert wav is None
    assert meta["ok"] is False
    assert "ffmpeg" in meta["reason"]
    assert "moov" in meta["reason"]
    assert mock_run.called, "expected subprocess.run to have been invoked"


def test_subprocess_timeout_returns_none(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """ffmpeg TimeoutExpired ⇒ (None, meta) — caller never sees an exception."""
    provider = LookaheadProvider()
    fake_file = tmp_path / "slow.flac"
    fake_file.write_bytes(b"fake-flac-data")

    monkeypatch.setattr(
        provider, "_current_position", lambda: ("SlowTrack", 1.0, 1.0)
    )
    monkeypatch.setattr(provider, "_resolve_file", lambda title: str(fake_file))

    def _raise_timeout(*args, **kwargs):  # noqa: ANN001 — mock signature
        raise subprocess.TimeoutExpired(cmd="ffmpeg", timeout=4.0)

    with patch(
        "vibemix.audio.lookahead.subprocess.run", side_effect=_raise_timeout
    ):
        wav, meta = provider.snapshot_wav()

    assert wav is None
    assert meta["ok"] is False
    assert "timeout" in meta["reason"].lower()


# ---------------------------------------------------------------------------
# Tests 6-7 — security / correctness gates on the ffmpeg invocation
# ---------------------------------------------------------------------------


def test_subprocess_args_use_list_form(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """V10 — ffmpeg invocation MUST use list-form argv (no shell=True)."""
    provider = LookaheadProvider()
    fake_file = tmp_path / "anything.mp3"
    fake_file.write_bytes(b"fake")

    monkeypatch.setattr(
        provider, "_current_position", lambda: ("AnyTrack", 1.0, 1.0)
    )
    monkeypatch.setattr(provider, "_resolve_file", lambda title: str(fake_file))

    fake_proc = MagicMock()
    fake_proc.returncode = 0
    fake_proc.stdout = b"RIFF" + b"\x00" * 1024
    fake_proc.stderr = b""

    with patch(
        "vibemix.audio.lookahead.subprocess.run", return_value=fake_proc
    ) as mock_run:
        provider.snapshot_wav()

    assert mock_run.called
    call_args, call_kwargs = mock_run.call_args
    argv = call_args[0]
    assert isinstance(argv, list), f"argv must be list, got {type(argv).__name__}"
    assert "shell" not in call_kwargs or call_kwargs["shell"] is False, (
        "shell=True is forbidden — V10 Malicious Code mitigation"
    )


def test_input_seek_before_dash_i(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Pattern 3 invariant: `-ss` MUST appear BEFORE `-i` (input-seek; ~100× faster)."""
    provider = LookaheadProvider()
    fake_file = tmp_path / "track.mp3"
    fake_file.write_bytes(b"fake")

    monkeypatch.setattr(
        provider, "_current_position", lambda: ("AnyTrack", 30.0, 1.0)
    )
    monkeypatch.setattr(provider, "_resolve_file", lambda title: str(fake_file))

    fake_proc = MagicMock()
    fake_proc.returncode = 0
    fake_proc.stdout = b"RIFF" + b"\x00" * 1024
    fake_proc.stderr = b""

    with patch(
        "vibemix.audio.lookahead.subprocess.run", return_value=fake_proc
    ) as mock_run:
        provider.snapshot_wav()

    argv = mock_run.call_args[0][0]
    assert "-ss" in argv, "ffmpeg argv missing -ss"
    assert "-i" in argv, "ffmpeg argv missing -i"
    assert argv.index("-ss") < argv.index("-i"), (
        "RESEARCH Pattern 3 invariant: `-ss` must precede `-i` (input seek). "
        f"Got argv={argv}"
    )


# ---------------------------------------------------------------------------
# Test 8 — extrapolation guard (Pitfall 2 defense)
# ---------------------------------------------------------------------------


def test_extrapolation_guard_on_title_change(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """On title CHANGE, `_current_position` MUST return the fresh raw elapsed.

    Pitfall 2: nowplaying-cli reports the last sample djay published; when the
    previous poll had the same title with the same elapsed, we extrapolate by
    wall-delta × rate. But when the TITLE changes (e.g. djay advanced to a new
    track), we must NOT extrapolate — return the fresh elapsed value verbatim.
    """
    provider = LookaheadProvider()

    # Seed with a "previous" poll for title "A" at elapsed 12.0 one second ago.
    provider._last_raw = {
        "kMRMediaRemoteNowPlayingInfoTitle": "A",
        "kMRMediaRemoteNowPlayingInfoElapsedTime": 12.0,
        "kMRMediaRemoteNowPlayingInfoPlaybackRate": 1.0,
    }
    provider._last_raw_wall = time.time() - 1.0

    # Now poll returns a DIFFERENT title at fresh elapsed 30.0.
    monkeypatch.setattr(
        provider,
        "_poll_raw",
        lambda: {
            "kMRMediaRemoteNowPlayingInfoTitle": "B",
            "kMRMediaRemoteNowPlayingInfoElapsedTime": 30.0,
            "kMRMediaRemoteNowPlayingInfoPlaybackRate": 1.0,
        },
    )

    title, pos, rate = provider._current_position()
    assert title == "B"
    assert rate == 1.0
    # Critical: pos is the FRESH 30.0 — NOT extrapolated (which would be ≈31.0).
    assert pos == 30.0, (
        f"title changed → must NOT extrapolate; expected 30.0, got {pos}"
    )
