# SPDX-License-Identifier: Apache-2.0
"""vibemix.ui_bus — ipc.* schema bridge for the Tauri shell.

Phase 11 Wave 0. The source-of-truth schema is the JSON file at
``tauri/ui/src/ipc/messages.schema.json``. This package mirrors it on the
Python side via hand-written ``@dataclass(frozen=True, slots=True)`` wrappers
+ a single ``jsonschema.Draft7Validator`` compiled at module import.

The Wave 4 WizardLoop will:
  * Construct outbound messages via ``StatusTick.make(...).to_json()``.
  * Validate inbound shell→sidecar frames via ``validator.parse_message``.

Wave 0 ships no WebSocket wiring — only the schema, dataclasses, validator,
and the CI gate ``scripts/check_ipc_schema.py``.
"""

from __future__ import annotations

from vibemix.ui_bus.messages import (
    # Phase 28 Plan 09 — Library IPC wrappers
    LibraryConfidence,
    LibraryConfidencePayload,
    LibraryImport,
    LibraryImportCancel,
    LibraryImportCancelPayload,
    LibraryImportPayload,
    LibraryImportProgress,
    LibraryImportProgressPayload,
    LibrarySearchRequest,
    LibrarySearchRequestPayload,
    LibrarySearchResult,
    LibrarySearchResultPayload,
    LibrarySimilarRequest,
    LibrarySimilarRequestPayload,
    LibrarySimilarResult,
    LibrarySimilarResultPayload,
    LibraryStalenessAction,
    LibraryStalenessActionPayload,
    LibraryStalenessNudge,
    LibraryStalenessNudgePayload,
    # Phase 32 — long-term DJ profile wrappers (PROFILE-04/05/07)
    ProfileConsentState,
    ProfileConsentStatePayload,
    ProfileDelete,
    ProfileDeleteAck,
    ProfileDeleteAckPayload,
    ProfileRegenerate,
    ProfileRegenerateResult,
    ProfileRegenerateResultPayload,
    ProfileSetConsent,
    ProfileSetConsentPayload,
    ProfileView,
    ProfileViewResult,
    ProfileViewResultPayload,
    # Wrapper dataclasses — one per schema oneOf entry (19 total)
    CalibrationAudioResult,
    # Payload-only structs (re-exported for type hints in downstream code)
    CalibrationAudioResultPayload,
    CalibrationDeviceList,
    CalibrationDeviceListPayload,
    CalibrationListDevices,
    CalibrationListDevicesPayload,
    CalibrationListWindows,
    CalibrationListWindowsPayload,
    CalibrationMidiEvent,
    CalibrationMidiEventPayload,
    CalibrationMidiTimeout,
    CalibrationMidiTimeoutPayload,
    CalibrationProbeAudio,
    CalibrationProbeAudioPayload,
    CalibrationSmokeTest,
    CalibrationSmokeTestDone,
    CalibrationSmokeTestDonePayload,
    CalibrationSmokeTestPayload,
    CalibrationSmokeTestStarted,
    CalibrationSmokeTestStartedPayload,
    CalibrationStartMidiListen,
    CalibrationStartMidiListenPayload,
    CalibrationUserHeardTone,
    CalibrationUserHeardTonePayload,
    CalibrationWindowList,
    CalibrationWindowListPayload,
    DeviceInfo,
    IpcBoot,
    IpcBootPayload,
    PermissionCheck,
    PermissionCheckPayload,
    PermissionState,
    PermissionStatePayload,
    StatusTick,
    StatusTickPayload,
    WindowInfo,
    WizardDone,
    WizardDonePayload,
    WizardStart,
    WizardStartPayload,
    # Phase 12 wrappers
    IpcError,
    IpcErrorPayload,
    LevelPair,
    # Phase 13 wrappers
    MascotMoodChange,
    MascotMoodChangePayload,
    MetersTriple,
    MidiEventEntry,
    PhaseChunk,
    # Phase 15-01 wrappers
    RecordingSummary,
    RecordingsDelete,
    RecordingsDeleteAck,
    RecordingsDeleteAckPayload,
    RecordingsDeletePayload,
    RecordingsEvents,
    RecordingsEventsPayload,
    RecordingsEventsResult,
    RecordingsEventsResultPayload,
    RecordingsList,
    RecordingsListPayload,
    RecordingsListResult,
    RecordingsListResultPayload,
    RecordingsUsage,
    RecordingsUsagePayload,
    # Phase 20-04 — citation diagnostics
    SessionCitation,
    # Phase 24-02 — overlay-highlight
    SessionOverlayHighlight,
    # Phase 25 Plan 25-03 — DEBRIEF architectural slot
    DebriefSessionLoaded,
    DebriefCitationSummary,
    DebriefEventTimeline,
    # Phase 29 Plan 29-03 — DEBRIEF v2.1 additive wrappers
    DebriefChapterList,
    DebriefTldrAudio,
    DebriefDrills,
    DebriefCitationTooltipReq,
    DebriefCitationTooltip,
    DebriefError,
    SessionMute,
    SessionMutePayload,
    SessionSnapshot,
    SessionSnapshotPayload,
    SettingsGet,
    SettingsGetPayload,
    SettingsSet,
    SettingsSetPayload,
    SettingsState,
    SettingsStatePayload,
    StatusRecheck,
    StatusRecheckPayload,
    TrackInfo,
    TranscriptLine,
)
from vibemix.ui_bus.schemas.citation import SessionCitationPayload
from vibemix.ui_bus.schemas.debrief import (
    ChapterRegionPayload,
    DebriefChapterListPayload,
    DebriefCitationSummaryPayload,
    DebriefCitationTooltipPayload,
    DebriefCitationTooltipReqPayload,
    DebriefDrillsPayload,
    DebriefErrorPayload,
    DebriefEventTimelinePayload,
    DebriefSessionLoadedPayload,
    DebriefTldrAudioPayload,
    DrillPayload,
)
from vibemix.ui_bus.schemas.overlay import SessionOverlayHighlightPayload
from vibemix.ui_bus.validator import parse_message, validate_message

__all__ = [
    "CalibrationAudioResult",
    "CalibrationAudioResultPayload",
    "CalibrationDeviceList",
    "CalibrationDeviceListPayload",
    "CalibrationListDevices",
    "CalibrationListDevicesPayload",
    "CalibrationListWindows",
    "CalibrationListWindowsPayload",
    "CalibrationMidiEvent",
    "CalibrationMidiEventPayload",
    "CalibrationMidiTimeout",
    "CalibrationMidiTimeoutPayload",
    "CalibrationProbeAudio",
    "CalibrationProbeAudioPayload",
    "CalibrationSmokeTest",
    "CalibrationSmokeTestDone",
    "CalibrationSmokeTestDonePayload",
    "CalibrationSmokeTestPayload",
    "CalibrationSmokeTestStarted",
    "CalibrationSmokeTestStartedPayload",
    "CalibrationStartMidiListen",
    "CalibrationStartMidiListenPayload",
    "CalibrationUserHeardTone",
    "CalibrationUserHeardTonePayload",
    "CalibrationWindowList",
    "CalibrationWindowListPayload",
    "DeviceInfo",
    "IpcBoot",
    "IpcBootPayload",
    "PermissionCheck",
    "PermissionCheckPayload",
    "PermissionState",
    "PermissionStatePayload",
    "StatusTick",
    "StatusTickPayload",
    "WindowInfo",
    "WizardDone",
    "WizardDonePayload",
    "WizardStart",
    "WizardStartPayload",
    # Phase 12
    "IpcError",
    "IpcErrorPayload",
    "LevelPair",
    # Phase 13
    "MascotMoodChange",
    "MascotMoodChangePayload",
    "MetersTriple",
    "MidiEventEntry",
    "PhaseChunk",
    # Phase 15-01
    "RecordingSummary",
    "RecordingsDelete",
    "RecordingsDeleteAck",
    "RecordingsDeleteAckPayload",
    "RecordingsDeletePayload",
    "RecordingsEvents",
    "RecordingsEventsPayload",
    "RecordingsEventsResult",
    "RecordingsEventsResultPayload",
    "RecordingsList",
    "RecordingsListPayload",
    "RecordingsListResult",
    "RecordingsListResultPayload",
    "RecordingsUsage",
    "RecordingsUsagePayload",
    # Phase 20-04
    "SessionCitation",
    "SessionCitationPayload",
    # Phase 24-02
    "SessionOverlayHighlight",
    "SessionOverlayHighlightPayload",
    # Phase 25 Plan 25-03 — DEBRIEF architectural slot
    "DebriefCitationSummary",
    "DebriefCitationSummaryPayload",
    "DebriefEventTimeline",
    "DebriefEventTimelinePayload",
    "DebriefSessionLoaded",
    "DebriefSessionLoadedPayload",
    # Phase 29 Plan 29-03 — DEBRIEF v2.1 additive wrappers
    "ChapterRegionPayload",
    "DebriefChapterList",
    "DebriefChapterListPayload",
    "DebriefCitationTooltip",
    "DebriefCitationTooltipPayload",
    "DebriefCitationTooltipReq",
    "DebriefCitationTooltipReqPayload",
    "DebriefDrills",
    "DebriefDrillsPayload",
    "DebriefError",
    "DebriefErrorPayload",
    "DebriefTldrAudio",
    "DebriefTldrAudioPayload",
    "DrillPayload",
    # Phase 28 Plan 09 — Library IPC
    "LibraryConfidence",
    "LibraryConfidencePayload",
    "LibraryImport",
    "LibraryImportCancel",
    "LibraryImportCancelPayload",
    "LibraryImportPayload",
    "LibraryImportProgress",
    "LibraryImportProgressPayload",
    "LibrarySearchRequest",
    "LibrarySearchRequestPayload",
    "LibrarySearchResult",
    "LibrarySearchResultPayload",
    "LibrarySimilarRequest",
    "LibrarySimilarRequestPayload",
    "LibrarySimilarResult",
    "LibrarySimilarResultPayload",
    "LibraryStalenessAction",
    "LibraryStalenessActionPayload",
    "LibraryStalenessNudge",
    "LibraryStalenessNudgePayload",
    # Phase 32 — long-term DJ profile (PROFILE-04/05/07)
    "ProfileConsentState",
    "ProfileConsentStatePayload",
    "ProfileDelete",
    "ProfileDeleteAck",
    "ProfileDeleteAckPayload",
    "ProfileRegenerate",
    "ProfileRegenerateResult",
    "ProfileRegenerateResultPayload",
    "ProfileSetConsent",
    "ProfileSetConsentPayload",
    "ProfileView",
    "ProfileViewResult",
    "ProfileViewResultPayload",
    "SessionMute",
    "SessionMutePayload",
    "SessionSnapshot",
    "SessionSnapshotPayload",
    "SettingsGet",
    "SettingsGetPayload",
    "SettingsSet",
    "SettingsSetPayload",
    "SettingsState",
    "SettingsStatePayload",
    "StatusRecheck",
    "StatusRecheckPayload",
    "TrackInfo",
    "TranscriptLine",
    "parse_message",
    "validate_message",
]
