# SPDX-License-Identifier: Apache-2.0
"""vibemix.ui_bus — ipc.* schema bridge for the Tauri shell.

Phase 11 Wave 0. The source-of-truth schema is the JSON file at
``tauri/ui/src/ipc/messages.schema.json``. This package mirrors it on the
Python side via hand-written ``@dataclass(frozen=True, slots=True)`` wrappers
+ a single ``jsonschema.Draft7Validator`` compiled at module import.

The Wave 4 WizardLoop will:
  * Construct outbound messages via ``StatusTick.make(...).to_json()``.
  * Validate inbound shell→sidecar frames via ``validator.parse_message``.

Wave 0 ships no WebSocket wiring — only the schema, dataclasses, validator,
and the CI gate ``scripts/check_ipc_schema.py``.
"""

from __future__ import annotations

from vibemix.ui_bus.learn_messages import (
    # Phase 92 TONE-02 / TONE-04 / LESSON-01..LESSON-06 / RENDER-04 —
    # lesson-runtime envelopes + the AI highlight contract.
    LearnAck,
    LearnAckPayload,
    LearnAdvance,
    LearnAdvancePayload,
    LearnCompleteLesson,
    LearnCompleteLessonPayload,
    # Phase 91 RENDER-01 / RENDER-02 / RENDER-07 — Learn module envelopes.
    LearnControllerDetected,
    LearnControllerDetectedPayload,
    LearnControlRect,
    LearnControlRectPayload,
    LearnExemplarPlay,
    LearnExemplarPlayPayload,
    LearnExemplarStop,
    LearnExemplarStopPayload,
    LearnExpectedAction,
    LearnHighlight,
    LearnHighlightPayload,
    LearnLessonLoaded,
    LearnLessonLoadedPayload,
    LearnLiveGrade,
    LearnLiveGradePayload,
    LearnMidiPosition,
    LearnMidiPositionPayload,
    LearnPlayheadDeck,
    LearnPlayheadTick,
    LearnPlayheadTickPayload,
    LearnProgressDot,
    LearnProgressState,
    LearnProgressStatePayload,
    LearnStartCourse,
    LearnStartCoursePayload,
    LearnStartLesson,
    LearnStartLessonPayload,
    LearnTeachingFocus,
    LearnTeachingFocusPayload,
    LearnTeachingLoopPayload,
    LearnTeachingObservationPayload,
    LearnTeachingVerificationPayload,
    LearnTutorSpeak,
    LearnTutorSpeakPayload,
    LearnWaveformDeck,
    LearnWaveformDeckCue,
    LearnWaveformReady,
    LearnWaveformReadyPayload,
)
from vibemix.ui_bus.messages import (
    # Wrapper dataclasses — one per schema oneOf entry (19 total)
    CalibrationAudioResult,
    # Payload-only structs (re-exported for type hints in downstream code)
    CalibrationAudioResultPayload,
    CalibrationDeviceList,
    CalibrationDeviceListPayload,
    CalibrationListDevices,
    CalibrationListDevicesPayload,
    CalibrationListWindows,
    CalibrationListWindowsPayload,
    CalibrationMidiEvent,
    CalibrationMidiEventPayload,
    CalibrationMidiTimeout,
    CalibrationMidiTimeoutPayload,
    CalibrationProbeAudio,
    CalibrationProbeAudioPayload,
    CalibrationSmokeTest,
    CalibrationSmokeTestDone,
    CalibrationSmokeTestDonePayload,
    CalibrationSmokeTestPayload,
    CalibrationSmokeTestStarted,
    CalibrationSmokeTestStartedPayload,
    CalibrationStartMidiListen,
    CalibrationStartMidiListenPayload,
    CalibrationUserHeardTone,
    CalibrationUserHeardTonePayload,
    CalibrationWindowList,
    CalibrationWindowListPayload,
    # Phase 29 Plan 29-03 — DEBRIEF v2.1 additive wrappers
    DebriefChapterList,
    DebriefCitationTooltip,
    DebriefCitationTooltipReq,
    DebriefDrills,
    DebriefError,
    DebriefMomentFeedback,
    DebriefNearMiss,
    # Phase 25 Plan 25-03 — DEBRIEF architectural slot
    DebriefSessionLoaded,
    DebriefTldrAudio,
    DeviceInfo,
    IpcBoot,
    IpcBootPayload,
    # Phase 12 wrappers
    IpcError,
    IpcErrorPayload,
    LevelPair,
    # Phase 28 Plan 09 — Library IPC wrappers
    LibraryImport,
    LibraryImportCancel,
    LibraryImportCancelPayload,
    LibraryImportPayload,
    LibraryImportProgress,
    LibraryImportProgressPayload,
    LibraryStalenessAction,
    LibraryStalenessActionPayload,
    LibraryStalenessNudge,
    LibraryStalenessNudgePayload,
    # Phase 13 wrappers
    MascotMoodChange,
    MascotMoodChangePayload,
    MetersTriple,
    MidiEventEntry,
    PermissionCheck,
    PermissionCheckPayload,
    PermissionState,
    PermissionStatePayload,
    PhaseChunk,
    # Phase 32 — long-term DJ profile wrappers (PROFILE-04/05/07)
    ProfileConsentState,
    ProfileConsentStatePayload,
    ProfileDelete,
    ProfileDeleteAck,
    ProfileDeleteAckPayload,
    ProfileRegenerate,
    ProfileRegenerateResult,
    ProfileRegenerateResultPayload,
    ProfileSetConsent,
    ProfileSetConsentPayload,
    ProfileView,
    ProfileViewResult,
    ProfileViewResultPayload,
    RecordingsDelete,
    RecordingsDeleteAck,
    RecordingsDeleteAckPayload,
    RecordingsDeletePayload,
    RecordingsEvents,
    RecordingsEventsPayload,
    RecordingsEventsResult,
    RecordingsEventsResultPayload,
    RecordingsList,
    RecordingsListPayload,
    RecordingsListResult,
    RecordingsListResultPayload,
    # Phase 15-01 wrappers
    RecordingSummary,
    RecordingsUsage,
    RecordingsUsagePayload,
    # Phase 20-04 — citation diagnostics
    SessionCitation,
    # Phase 44-03 — cohost reaction broadcast (LAUNCH-02)
    SessionCohostReaction,
    SessionMute,
    SessionMutePayload,
    # Phase 24-02 — overlay-highlight
    SessionOverlayHighlight,
    SessionSetMode,
    SessionSetModePayload,
    SessionSnapshot,
    SessionSnapshotPayload,
    SessionStart,
    SessionStartPayload,
    SessionStop,
    SessionStopPayload,
    SettingsBrainAck,
    SettingsBrainAckPayload,
    SettingsGet,
    SettingsGetPayload,
    SettingsSet,
    SettingsSetBrain,
    SettingsSetBrainPayload,
    SettingsSetPayload,
    SettingsState,
    SettingsStatePayload,
    StatusRecheck,
    StatusRecheckPayload,
    StatusTick,
    StatusTickPayload,
    TrackInfo,
    TranscriptLine,
    WindowInfo,
    WizardDone,
    WizardDonePayload,
    WizardSetSkill,
    WizardSetSkillPayload,
    WizardStart,
    WizardStartPayload,
)
from vibemix.ui_bus.schemas.citation import SessionCitationPayload
from vibemix.ui_bus.schemas.cohost_reaction import (
    CitationChipPayload,
    SessionCohostReactionPayload,
)
from vibemix.ui_bus.schemas.debrief import (
    ChapterRegionPayload,
    DebriefChapterListPayload,
    DebriefCitationTooltipPayload,
    DebriefCitationTooltipReqPayload,
    DebriefDrillsPayload,
    DebriefErrorPayload,
    DebriefMomentFeedbackPayload,
    DebriefNearMissPayload,
    DebriefSessionLoadedPayload,
    DebriefTldrAudioPayload,
    DrillPayload,
    LearnReferralPayload,
)
from vibemix.ui_bus.schemas.overlay import SessionOverlayHighlightPayload
from vibemix.ui_bus.validator import parse_message, validate_message

__all__ = [
    "CalibrationAudioResult",
    "CalibrationAudioResultPayload",
    "CalibrationDeviceList",
    "CalibrationDeviceListPayload",
    "CalibrationListDevices",
    "CalibrationListDevicesPayload",
    "CalibrationListWindows",
    "CalibrationListWindowsPayload",
    "CalibrationMidiEvent",
    "CalibrationMidiEventPayload",
    "CalibrationMidiTimeout",
    "CalibrationMidiTimeoutPayload",
    "CalibrationProbeAudio",
    "CalibrationProbeAudioPayload",
    "CalibrationSmokeTest",
    "CalibrationSmokeTestDone",
    "CalibrationSmokeTestDonePayload",
    "CalibrationSmokeTestPayload",
    "CalibrationSmokeTestStarted",
    "CalibrationSmokeTestStartedPayload",
    "CalibrationStartMidiListen",
    "CalibrationStartMidiListenPayload",
    "CalibrationUserHeardTone",
    "CalibrationUserHeardTonePayload",
    "CalibrationWindowList",
    "CalibrationWindowListPayload",
    "DeviceInfo",
    "IpcBoot",
    "IpcBootPayload",
    "PermissionCheck",
    "PermissionCheckPayload",
    "PermissionState",
    "PermissionStatePayload",
    "StatusTick",
    "StatusTickPayload",
    "WindowInfo",
    "WizardDone",
    "WizardDonePayload",
    "WizardSetSkill",
    "WizardSetSkillPayload",
    "WizardStart",
    "WizardStartPayload",
    # Phase 12
    "IpcError",
    "IpcErrorPayload",
    "LevelPair",
    # Phase 13
    "MascotMoodChange",
    "MascotMoodChangePayload",
    "MetersTriple",
    "MidiEventEntry",
    "PhaseChunk",
    # Phase 15-01
    "RecordingSummary",
    "RecordingsDelete",
    "RecordingsDeleteAck",
    "RecordingsDeleteAckPayload",
    "RecordingsDeletePayload",
    "RecordingsEvents",
    "RecordingsEventsPayload",
    "RecordingsEventsResult",
    "RecordingsEventsResultPayload",
    "RecordingsList",
    "RecordingsListPayload",
    "RecordingsListResult",
    "RecordingsListResultPayload",
    "RecordingsUsage",
    "RecordingsUsagePayload",
    # Phase 20-04
    "SessionCitation",
    "SessionCitationPayload",
    # Phase 24-02
    "SessionOverlayHighlight",
    "SessionOverlayHighlightPayload",
    # Phase 44-03 — cohost reaction broadcast (LAUNCH-02)
    "CitationChipPayload",
    "SessionCohostReaction",
    "SessionCohostReactionPayload",
    # Phase 25 Plan 25-03 — DEBRIEF architectural slot
    "DebriefSessionLoaded",
    "DebriefSessionLoadedPayload",
    # Phase 29 Plan 29-03 — DEBRIEF v2.1 additive wrappers
    "ChapterRegionPayload",
    "DebriefChapterList",
    "DebriefChapterListPayload",
    "DebriefCitationTooltip",
    "DebriefCitationTooltipPayload",
    "DebriefCitationTooltipReq",
    "DebriefCitationTooltipReqPayload",
    "DebriefDrills",
    "DebriefDrillsPayload",
    "DebriefError",
    "DebriefErrorPayload",
    "DebriefMomentFeedback",
    "DebriefMomentFeedbackPayload",
    "DebriefNearMiss",
    "DebriefNearMissPayload",
    "DebriefTldrAudio",
    "DebriefTldrAudioPayload",
    "DrillPayload",
    "LearnReferralPayload",
    # Phase 28 Plan 09 — Library IPC
    "LibraryImport",
    "LibraryImportCancel",
    "LibraryImportCancelPayload",
    "LibraryImportPayload",
    "LibraryImportProgress",
    "LibraryImportProgressPayload",
    "LibraryStalenessAction",
    "LibraryStalenessActionPayload",
    "LibraryStalenessNudge",
    "LibraryStalenessNudgePayload",
    # Phase 91 RENDER-01 / RENDER-02 / RENDER-07 — Learn module envelopes
    "LearnControllerDetected",
    "LearnControllerDetectedPayload",
    "LearnMidiPosition",
    "LearnMidiPositionPayload",
    # Organism focus mechanic — teaching_focus + control_rect relay
    "LearnTeachingFocus",
    "LearnTeachingFocusPayload",
    "LearnControlRect",
    "LearnControlRectPayload",
    # Phase 92 TONE-02 / TONE-04 / LESSON-01..LESSON-06 / RENDER-04 —
    # lesson-runtime envelopes + AI highlight contract
    "LearnAck",
    "LearnAckPayload",
    "LearnAdvance",
    "LearnAdvancePayload",
    "LearnCompleteLesson",
    "LearnCompleteLessonPayload",
    "LearnExemplarPlay",
    "LearnExemplarPlayPayload",
    "LearnExemplarStop",
    "LearnExemplarStopPayload",
    "LearnExpectedAction",
    "LearnHighlight",
    "LearnHighlightPayload",
    "LearnLessonLoaded",
    "LearnLessonLoadedPayload",
    "LearnLiveGrade",
    "LearnLiveGradePayload",
    "LearnPlayheadDeck",
    "LearnPlayheadTick",
    "LearnPlayheadTickPayload",
    "LearnProgressDot",
    "LearnProgressState",
    "LearnProgressStatePayload",
    "LearnStartCourse",
    "LearnStartCoursePayload",
    "LearnStartLesson",
    "LearnStartLessonPayload",
    "LearnTeachingLoopPayload",
    "LearnTeachingObservationPayload",
    "LearnTeachingVerificationPayload",
    "LearnTutorSpeak",
    "LearnTutorSpeakPayload",
    "LearnWaveformDeck",
    "LearnWaveformDeckCue",
    "LearnWaveformReady",
    "LearnWaveformReadyPayload",
    # Phase 32 — long-term DJ profile (PROFILE-04/05/07)
    "ProfileConsentState",
    "ProfileConsentStatePayload",
    "ProfileDelete",
    "ProfileDeleteAck",
    "ProfileDeleteAckPayload",
    "ProfileRegenerate",
    "ProfileRegenerateResult",
    "ProfileRegenerateResultPayload",
    "ProfileSetConsent",
    "ProfileSetConsentPayload",
    "ProfileView",
    "ProfileViewResult",
    "ProfileViewResultPayload",
    "SessionMute",
    "SessionMutePayload",
    "SessionSetMode",
    "SessionSetModePayload",
    "SessionSnapshot",
    "SessionSnapshotPayload",
    "SessionStart",
    "SessionStartPayload",
    "SessionStop",
    "SessionStopPayload",
    "SettingsBrainAck",
    "SettingsBrainAckPayload",
    "SettingsGet",
    "SettingsGetPayload",
    "SettingsSet",
    "SettingsSetBrain",
    "SettingsSetBrainPayload",
    "SettingsSetPayload",
    "SettingsState",
    "SettingsStatePayload",
    "StatusRecheck",
    "StatusRecheckPayload",
    "TrackInfo",
    "TranscriptLine",
    "parse_message",
    "validate_message",
]
