# SPDX-License-Identifier: Apache-2.0
"""vibemix.ui_bus — ipc.* schema bridge for the Tauri shell.

Phase 11 Wave 0. The source-of-truth schema is the JSON file at
``tauri/ui/src/ipc/messages.schema.json``. This package mirrors it on the
Python side via hand-written ``@dataclass(frozen=True, slots=True)`` wrappers
+ a single ``jsonschema.Draft7Validator`` compiled at module import.

The Wave 4 WizardLoop will:
  * Construct outbound messages via ``StatusTick.make(...).to_json()``.
  * Validate inbound shell→sidecar frames via ``validator.parse_message``.

Wave 0 ships no WebSocket wiring — only the schema, dataclasses, validator,
and the CI gate ``scripts/check_ipc_schema.py``.
"""

from __future__ import annotations

from vibemix.ui_bus.messages import (
    # Wrapper dataclasses — one per schema oneOf entry (19 total)
    CalibrationAudioResult,
    # Payload-only structs (re-exported for type hints in downstream code)
    CalibrationAudioResultPayload,
    CalibrationDeviceList,
    CalibrationDeviceListPayload,
    CalibrationListDevices,
    CalibrationListDevicesPayload,
    CalibrationListWindows,
    CalibrationListWindowsPayload,
    CalibrationMidiEvent,
    CalibrationMidiEventPayload,
    CalibrationMidiTimeout,
    CalibrationMidiTimeoutPayload,
    CalibrationProbeAudio,
    CalibrationProbeAudioPayload,
    CalibrationSmokeTest,
    CalibrationSmokeTestDone,
    CalibrationSmokeTestDonePayload,
    CalibrationSmokeTestPayload,
    CalibrationSmokeTestStarted,
    CalibrationSmokeTestStartedPayload,
    CalibrationStartMidiListen,
    CalibrationStartMidiListenPayload,
    CalibrationUserHeardTone,
    CalibrationUserHeardTonePayload,
    CalibrationWindowList,
    CalibrationWindowListPayload,
    DeviceInfo,
    IpcBoot,
    IpcBootPayload,
    PermissionCheck,
    PermissionCheckPayload,
    PermissionState,
    PermissionStatePayload,
    StatusTick,
    StatusTickPayload,
    WindowInfo,
    WizardDone,
    WizardDonePayload,
    WizardStart,
    WizardStartPayload,
    # Phase 12 wrappers
    IpcError,
    IpcErrorPayload,
    LevelPair,
    # Phase 13 wrappers
    MascotMoodChange,
    MascotMoodChangePayload,
    MetersTriple,
    MidiEventEntry,
    PhaseChunk,
    SessionMute,
    SessionMutePayload,
    SessionSnapshot,
    SessionSnapshotPayload,
    SettingsGet,
    SettingsGetPayload,
    SettingsSet,
    SettingsSetPayload,
    SettingsState,
    SettingsStatePayload,
    StatusRecheck,
    StatusRecheckPayload,
    TrackInfo,
    TranscriptLine,
)
from vibemix.ui_bus.validator import parse_message, validate_message

__all__ = [
    "CalibrationAudioResult",
    "CalibrationAudioResultPayload",
    "CalibrationDeviceList",
    "CalibrationDeviceListPayload",
    "CalibrationListDevices",
    "CalibrationListDevicesPayload",
    "CalibrationListWindows",
    "CalibrationListWindowsPayload",
    "CalibrationMidiEvent",
    "CalibrationMidiEventPayload",
    "CalibrationMidiTimeout",
    "CalibrationMidiTimeoutPayload",
    "CalibrationProbeAudio",
    "CalibrationProbeAudioPayload",
    "CalibrationSmokeTest",
    "CalibrationSmokeTestDone",
    "CalibrationSmokeTestDonePayload",
    "CalibrationSmokeTestPayload",
    "CalibrationSmokeTestStarted",
    "CalibrationSmokeTestStartedPayload",
    "CalibrationStartMidiListen",
    "CalibrationStartMidiListenPayload",
    "CalibrationUserHeardTone",
    "CalibrationUserHeardTonePayload",
    "CalibrationWindowList",
    "CalibrationWindowListPayload",
    "DeviceInfo",
    "IpcBoot",
    "IpcBootPayload",
    "PermissionCheck",
    "PermissionCheckPayload",
    "PermissionState",
    "PermissionStatePayload",
    "StatusTick",
    "StatusTickPayload",
    "WindowInfo",
    "WizardDone",
    "WizardDonePayload",
    "WizardStart",
    "WizardStartPayload",
    # Phase 12
    "IpcError",
    "IpcErrorPayload",
    "LevelPair",
    # Phase 13
    "MascotMoodChange",
    "MascotMoodChangePayload",
    "MetersTriple",
    "MidiEventEntry",
    "PhaseChunk",
    "SessionMute",
    "SessionMutePayload",
    "SessionSnapshot",
    "SessionSnapshotPayload",
    "SettingsGet",
    "SettingsGetPayload",
    "SettingsSet",
    "SettingsSetPayload",
    "SettingsState",
    "SettingsStatePayload",
    "StatusRecheck",
    "StatusRecheckPayload",
    "TrackInfo",
    "TranscriptLine",
    "parse_message",
    "validate_message",
]
