# SPDX-License-Identifier: Apache-2.0
"""Frontend navigation projection generated from the Python curriculum."""
from __future__ import annotations

import json
import re
from typing import Any

from vibemix.learn.curriculum import (
    COURSE_REGISTRY,
    CURRICULUM,
    beginner_course_ids,
    beginner_lesson_ids,
)


def beginner_curriculum_projection() -> dict[str, list[dict[str, Any]]]:
    """Return the Learn chooser's course + lesson projection.

    This is intentionally smaller than ``LessonMeta``. The frontstage chooser
    needs labels, unlock gates, lock reasons, lesson ids, course ids, and
    titles; expected actions and tutor copy stay on the Python side.
    """
    course_ids = beginner_course_ids()
    lessons = []
    for lesson_id in beginner_lesson_ids():
        meta = CURRICULUM[lesson_id]
        lessons.append(
            {
                "lesson_id": lesson_id,
                "course_id": meta.course_id,
                "title": meta.title,
            }
        )
    courses = [
        {
            "course_id": course_id,
            "label": COURSE_REGISTRY[course_id].label,
            "hud_label": COURSE_REGISTRY[course_id].hud_label,
            "unlock_gate": COURSE_REGISTRY[course_id].unlock_gate,
            "lock_reason": COURSE_REGISTRY[course_id].lock_reason,
            "frontstage_mode": COURSE_REGISTRY[course_id].frontstage_mode,
            "capabilities": list(COURSE_REGISTRY[course_id].capabilities),
        }
        for course_id in course_ids
    ]
    return {"courses": courses, "lessons": lessons}


def render_curriculum_meta_ts() -> str:
    """Render ``tauri/ui/src/learn/lesson/curriculum-meta.ts``."""
    projection = beginner_curriculum_projection()
    gates = sorted(
        {
            str(course["unlock_gate"])
            for course in projection["courses"]
            if course.get("unlock_gate")
        }
    )
    gate_type = " | ".join(json.dumps(gate) for gate in gates) or "never"
    progress_gate_rows = "".join(
        f"  {_ts_progress_field(gate)}?: boolean;\n" for gate in gates
    )
    frontstage_modes = sorted(
        {str(course["frontstage_mode"]) for course in projection["courses"]}
    )
    frontstage_mode_type = (
        " | ".join(json.dumps(mode) for mode in frontstage_modes) or "never"
    )
    capabilities = sorted(
        {
            str(capability)
            for course in projection["courses"]
            for capability in course["capabilities"]
        }
    )
    capability_type = (
        " | ".join(json.dumps(capability) for capability in capabilities)
        or "never"
    )
    course_rows = ",\n".join(
        "  "
        + json.dumps(course["course_id"], ensure_ascii=False)
        + ": "
        + _ts_object(
            {
                "label": course["label"],
                "hud_label": course["hud_label"],
                "unlock_gate": course["unlock_gate"],
                "lock_reason": course["lock_reason"],
                "frontstage_mode": course["frontstage_mode"],
                "capabilities": course["capabilities"],
            }
        )
        for course in projection["courses"]
    )
    lesson_rows = ",\n".join(
        "  "
        + _ts_object(
            {
                "lesson_id": lesson["lesson_id"],
                "course_id": lesson["course_id"],
                "title": lesson["title"],
            }
        )
        for lesson in projection["lessons"]
    )
    return (
        "// SPDX-License-Identifier: Apache-2.0\n"
        "//\n"
        "// Generated by scripts/export_learn_curriculum_meta.py.\n"
        "// Source of truth: src/vibemix/learn/curriculum.py.\n"
        "\n"
        'import type { ProgressListEntry, LessonStatus } from "./progress-list.js";\n'
        "\n"
        f"type CourseUnlockGate = {gate_type};\n"
        f"type CourseFrontstageMode = {frontstage_mode_type};\n"
        f"type CourseCapability = {capability_type};\n"
        "\n"
        "interface CourseRegistryRow {\n"
        "  label: string;\n"
        "  hud_label: string;\n"
        "  unlock_gate: CourseUnlockGate | null;\n"
        "  lock_reason: string | null;\n"
        "  frontstage_mode: CourseFrontstageMode;\n"
        "  capabilities: readonly CourseCapability[];\n"
        "}\n"
        "\n"
        "export const COURSE_REGISTRY = {\n"
        f"{course_rows},\n"
        "} as const satisfies Readonly<Record<string, CourseRegistryRow>>;\n"
        "\n"
        "export type CourseId = keyof typeof COURSE_REGISTRY;\n"
        "\n"
        "export const COURSE_LABELS = Object.freeze(\n"
        "  Object.fromEntries(\n"
        "    Object.entries(COURSE_REGISTRY).map(([courseId, row]) => [\n"
        "      courseId,\n"
        "      row.label,\n"
        "    ]),\n"
        "  ),\n"
        ") as Readonly<Record<CourseId, string>>;\n"
        "\n"
        "interface CurriculumMetaRow {\n"
        '  lesson_id: string; // "L1.01" - what curriculum.py keys CURRICULUM with\n'
        "  course_id: CourseId;\n"
        "  title: string;\n"
        "}\n"
        "\n"
        "export interface LearnProgressProjection {\n"
        "  lessons?: Record<\n"
        "    string,\n"
        "    {\n"
        "      completed?: boolean;\n"
        "      completed_at?: string | null;\n"
        "      strikes_used?: number;\n"
        "      practice_sources?: { hardware?: number; screen?: number };\n"
        '      last_practice_source?: "hardware" | "screen" | null;\n'
        "    } | undefined\n"
        "  >;\n"
        f"{progress_gate_rows}"
        "  [key: string]: unknown;\n"
        "}\n"
        "\n"
        "/** Canonical lesson order generated from Python CURRICULUM. */\n"
        "export const CURRICULUM_META: ReadonlyArray<CurriculumMetaRow> = [\n"
        f"{lesson_rows},\n"
        "];\n"
        "\n"
        "export function firstRecommendedLessonId(\n"
        "  progress: LearnProgressProjection | null = null,\n"
        "): string {\n"
        "  const entries = buildProgressEntries(progress);\n"
        "  return (\n"
        "    entries.find((entry) => entry.is_recommended)?.lesson_id ??\n"
        "    entries.find((entry) => !entry.locked)?.lesson_id ??\n"
        "    CURRICULUM_META[0]?.lesson_id ??\n"
        '    "L1.01"\n'
        "  );\n"
        "}\n"
        "\n"
        "/** Project the static curriculum mirror onto the progress-list shape. */\n"
        "export function buildProgressEntries(\n"
        "  progress: LearnProgressProjection | null,\n"
        "): ProgressListEntry[] {\n"
        "  const lessonsMap = progress?.lessons ?? {};\n"
        "  const projected: ProgressListEntry[] = CURRICULUM_META.map((meta) => {\n"
        "    const legacyKey = Object.keys(lessonsMap).find((key) =>\n"
        "      key.startsWith(`${meta.lesson_id}-`),\n"
        "    );\n"
        "    const entry = lessonsMap[meta.lesson_id] ?? (\n"
        "      legacyKey ? lessonsMap[legacyKey] : undefined\n"
        "    );\n"
        '    let status: LessonStatus = "empty";\n'
        "    if (entry?.completed) {\n"
        '      status = "completed";\n'
        "    } else if (\n"
        "      entry?.completed === false ||\n"
        "      (entry?.strikes_used && entry.strikes_used > 0)\n"
        "    ) {\n"
        '      status = "in-progress";\n'
        "    }\n"
        "    const courseUnlocked = isCourseUnlocked(meta.course_id, progress);\n"
        '    const locked = !courseUnlocked && status !== "completed";\n'
        "    return {\n"
        "      lesson_id: meta.lesson_id,\n"
        "      title: meta.title,\n"
        "      course_id: meta.course_id,\n"
        "      course_label: COURSE_LABELS[meta.course_id],\n"
        "      status,\n"
        "      strikes_used: entry?.strikes_used,\n"
        "      locked,\n"
        "      lock_reason: locked ? lockReason(meta.course_id) : undefined,\n"
        "    };\n"
        "  });\n"
        "  const recommended = (\n"
        "    projected.find(\n"
        '      (entry) => !entry.locked && entry.status === "in-progress",\n'
        "    ) ??\n"
        "    projected.find(\n"
        '      (entry) => !entry.locked && entry.status !== "completed",\n'
        "    ) ??\n"
        "    projected.find((entry) => !entry.locked)\n"
        "  );\n"
        "  if (recommended) recommended.is_recommended = true;\n"
        "  return projected;\n"
        "}\n"
        "\n"
        "function isCourseUnlocked(\n"
        "  course_id: CourseId,\n"
        "  progress: LearnProgressProjection | null,\n"
        "): boolean {\n"
        "  const gate = COURSE_REGISTRY[course_id]?.unlock_gate;\n"
        "  if (!gate) return true;\n"
        "  return progress?.[gate] === true;\n"
        "}\n"
        "\n"
        "function lockReason(course_id: CourseId): string {\n"
        '  return COURSE_REGISTRY[course_id]?.lock_reason ?? "locked";\n'
        "}\n"
    )


def _ts_object(values: dict[str, Any]) -> str:
    parts = []
    for key, value in values.items():
        parts.append(f"{key}: {json.dumps(value, ensure_ascii=False)}")
    return "{ " + ", ".join(parts) + " }"


def _ts_progress_field(gate: str) -> str:
    if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", gate):
        return gate
    return json.dumps(gate, ensure_ascii=False)
